//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportCard
    {
        public int TransportCardId { get; set; }
        public string TransportCardNumber { get; set; }
        public int TransportCardRoleId { get; set; }
        public int CurrentLoad { get; set; }
        public System.DateTime LastUsedDate { get; set; }
    
        public virtual TransportCard TransportCard1 { get; set; }
        public virtual TransportCard TransportCard2 { get; set; }
        public virtual TransportCardRole TransportCardRole { get; set; }
        public virtual TransportCardLog TransportCardLog { get; set; }
    }
}
