//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportCardRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportCardRole()
        {
            this.TransportCards = new HashSet<TransportCard>();
        }
    
        public int TransportCardRoleId { get; set; }
        public string TransportCardRoleName { get; set; }
        public Nullable<decimal> TransportCardRoleDiscount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportCard> TransportCards { get; set; }
    }
}
